# ------------------------------ tabstop = 4 ----------------------------------
#
# If not stated otherwise in this file or this component's LICENSE file the
# following copyright and licenses apply:
#
# Copyright 2024 Comcast Cable Communications Management, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#
# ------------------------------ tabstop = 4 ----------------------------------

#
# Created by Kevin Funderburg on 09/20/2024
#

# Setting the name element to the user helps keep the container name easy to identify
# by namespacing it with the user's name. Example: $USER-barton-1
name: $BUILDER_USER

services:
    barton:
        image: barton_builder_$BUILDER_USER
        network_mode: bridge

        # If the the image must be built, a few environment variables must be set. The devcontainer
        # will take care of this for you, but if you want to build from the CLI, leverage dockerw
        # to handle setting these variables and the compose commands.
        build:
            context: .
            dockerfile: Dockerfile

            # This top level compose build target will set up the barton environment, but specifically exludes
            # non-root user creation. Non-root user creation is handled in the extended compose.devcontainer.yaml.
            # The primary reason to separate the two is to allow for a Barton image to be built
            # on the CLI without hardcoding a specific user into the image. Useful when operating
            # on a shared machine.
            target: third_party_builder

        cap_add:
            - SYS_PTRACE
            - PERFMON
        device_cgroup_rules:
            - 'a 189:* rmw'
        extra_hosts:
            - "host.docker.internal:host-gateway"
        privileged: true
        security_opt:
            - seccomp:unconfined
        volumes:
            # Mount the barton source code on the host into the same path within container.
            - ..:/$BARTON_TOP:cached
