# ------------------------------ tabstop = 4 ----------------------------------
#
# If not stated otherwise in this file or this component's LICENSE file the
# following copyright and licenses apply:
#
# Copyright 2024 Comcast Cable Communications Management, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#
# ------------------------------ tabstop = 4 ----------------------------------

#
# Created by Raiyan Chowdhury on 12/12/2024
#

name: Check Copyright Headers

on:
    pull_request:

jobs:

    check_copyright_headers:
        name: Check Copyright Headers on Added and Modified Files
        runs-on: ubuntu-latest

        steps:
            -
                name: Checkout code
                uses: actions/checkout@v4
                with:
                    repository: ${{ github.repository }}
                    token: ${{ secrets.RDKCM_BARTON }}

            -
                name: Get list of added and modified files
                run: |
                    git fetch origin ${{ github.event.pull_request.base.ref }}
                    git diff --diff-filter=ACM --name-only origin/${{ github.event.pull_request.base.ref }} > changed_files.txt

            -
                name: Check for copyright headers
                env:
                    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    PR: ${{ github.event.pull_request.number }}
                run: |
                    COPYRIGHT_HEADER_SLASH=$(cat docs/copyright-header-slash.txt)
                    COPYRIGHT_HEADER_HASH=$(cat docs/copyright-header-hash.txt)

                    missing_header=false
                    bad_files="/tmp/bad_files.txt"
                    echo "Missing or incorrect copyright headers in the following files:" > $bad_files

                    while read -r file; do
                        if [[ "$file" == *.c || "$file" == *.h || "$file" == *.cpp || "$file" == *.hpp ]]; then
                            if ! awk -v pattern="$COPYRIGHT_HEADER_SLASH" 'BEGIN { found=0 } { content = content $0 "\n" } END { if (index(content, pattern) != 0) found=1 } END { exit !found }' "$file"; then
                                echo "Missing or incorrect copyright header in $file"
                                echo "$file" >> $bad_files
                                missing_header=true
                            fi
                        elif [[ "$file" == *.sh || "$file" == *.yaml || "$file" == *.cmake || "$file" == *.py || "$file" == *CMakeLists.txt ]]; then
                            if ! awk -v pattern="$COPYRIGHT_HEADER_HASH" 'BEGIN { found=0 } { content = content $0 "\n" } END { if (index(content, pattern) != 0) found=1 } END { exit !found }' "$file"; then
                                echo "Missing or incorrect copyright header in $file"
                                echo "$file" >> $bad_files
                                missing_header=true
                            fi
                        fi
                    done < changed_files.txt

                    if [ "$missing_header" = true ]; then
                        gh pr comment $PR -b "$(cat $bad_files)"
                        rm /tmp/bad_files.txt
                        exit 1
                    fi
